### ISSUE TITLE
Poder ver eventos que já aconteceram.

### ISSUE THREAD

**Issue by ByIvo** [DeveloperParana/devmx#57]
Objetivos:
 - Dessa forma as pessoas conseguem ver os eventos que aconteceram no passado
 - As pessoas podem acessar o álbum de um evento passado
 - Podemos compartilhar eventos que já aconteceram (Por exemplo, para comprovar a parceria com a FIAP que fizemos em 2024)

**Comment by guiseek** [comment]
Boa @ByIvo! implementaremos isso logo que concluirmos a primeira versão da página de eventos pública
